language: python
python:
  - "2.7"
  - "3.6"
env:
  - DJANGO=1.11

before_install:
  - sudo apt-get install tidy
  - sudo apt-get install -y libreoffice python3-uno
  - libreoffice '--accept=socket,host=127.0.0.1,port=8100;urp;' &

install:
  - pip install -U setuptools
  - pip install coveralls
  - pip install Django==$DJANGO
  - pip install -U pytest-cov
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -r requirements.python3.txt; else pip install -r requirements.txt;  fi
#  - test -e "requirements.$TRAVIS_BRANCH.txt" && ( pip install -r "requirements.$TRAVIS_BRANCH.txt" ) || ( pip install -r requirements.txt )
  - pip install -e .

script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - # if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then inv cov; fi
  - inv prep test

after_success:
  - coveralls

